
services:
  # Serviço do Back-end
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Serviço do Front-end
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true